AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ProjectName:
    Type : 'String'
    Default: 'ecs'
    Description: Identifies a Project Name
  ProjectEnvironment:
    Type : 'String'
    Default: 'test'
    Description: Identifies a Project Environment
  CreatedBy:
    Type : 'String'
    Default: 'Suleman'
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${ProjectName}-EcsFlaskMongoCluster-${ProjectEnvironment}'
      Tags:
        - Key: "Name"
          Value: !Sub '${ProjectName}-EcsFlaskMongoCluste-${ProjectEnvironment}'
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Environment"
          Value: !Ref ProjectEnvironment
        - Key: "Stack"
          Value: !Ref AWS::StackName
        - Key: "CreatedBy"
          Value: !Ref CreatedBy
Outputs:
  ClusterName:
    Description: This is the cluster name which will be used inside launch configuration when it try to 
    # connect teh cluster.
    Value: !Ref ECSCluster