AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  ProjectName:
    Type : 'String'
    Default: 'ecs'
    Description: Identifies a Project Name
  ProjectEnvironment:
    Type : 'String'
    Default: 'test'
    Description: Identifies a Project Environment
  CreatedBy:
    Type : 'String'
    Default: 'Suleman'
Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      Tags:
        - Key: "Name"
          Value: !Sub '${ProjectName}-EcsRole-${ProjectEnvironment}'
        - Key: "Project"
          Value: !Ref ProjectName
        - Key: "Environment"
          Value: !Ref ProjectEnvironment
        - Key: "Stack"
          Value: !Ref AWS::StackName
        - Key: "CreatedBy"
          Value: !Ref CreatedBy
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: !Sub '${ProjectName}-ECSforEC2InstanceRolePolicy-${ProjectEnvironment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Effect: Allow
                Action:
                - "ecs:CreateCluster"
                - "ecs:DeregisterContainerInstance"
                - "ecs:DiscoverPollEndpoint"
                - "ecs:Poll"
                - "ecs:RegisterContainerInstance"
                - "ecs:StartTelemetrySession"
                - "ecs:Submit*"
                - "ecr:GetAuthorizationToken"
                - "ecr:BatchCheckLayerAvailability"
                - "ecr:GetDownloadUrlForLayer"
                - "ecr:BatchGetImage"
                - "logs:CreateLogStream"
                - "logs:PutLogEvents"
                Resource: "*"
        - PolicyName: !Sub '${ProjectName}-RexrayPolicy-${ProjectEnvironment}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Effect: Allow
                Action:
                - "ec2:AttachVolume"
                - "ec2:CreateVolume"
                - "ec2:CreateSnapshot"
                - "ec2:CreateTags"
                - "ec2:DeleteVolume"
                - "ec2:DeleteSnapshot"
                - "ec2:DescribeAvailabilityZones"
                - "ec2:DescribeInstances"
                - "ec2:DescribeVolumes"
                - "ec2:DescribeVolumeAttribute"
                - "ec2:DescribeVolumeStatus"
                - "ec2:DescribeSnapshots"
                - "ec2:CopySnapshot"
                - "ec2:DescribeSnapshotAttribute"
                - "ec2:DetachVolume"
                - "ec2:ModifySnapshotAttribute"
                - "ec2:ModifyVolumeAttribute"
                - "ec2:DescribeTags"
                Resource: "*"
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - Ref: EC2Role
Outputs:
  EC2InstanceProfile:
    Description: This will be attached with Ecs Worker EC2 instances in launch configuration.
    Value: !Ref EC2InstanceProfile